M48
; DRILL file {KiCad 6.0.6} date Di 30 Aug 2022 17:09:13 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-30T17:09:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.2205Y-3.2874
X1.2205Y-3.9567
X2.4016Y-3.2874
X2.4016Y-3.9567
T0
M30
